name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        run: |
          npx angular-cli-ghpages \
            --dir=dist/portfolio-app/browser \
            --repo=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MartinoFCR/portfolio.git \
            --branch=gh-pages \
            --no-silent


